// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6LTiu-1PfFXaUlfnnkKtNT2YgWeryAU4',
    appId: '1:162718586351:web:1059f51c25b9f944fe121a',
    messagingSenderId: '162718586351',
    projectId: 'zoho-9e3e8',
    authDomain: 'zoho-9e3e8.firebaseapp.com',
    storageBucket: 'zoho-9e3e8.firebasestorage.app',
    measurementId: 'G-DD818QZ1KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABFeF4UTTM7bpD3n5qmyUjQuVNXc1vy80',
    appId: '1:162718586351:android:582d0ba136b8af05fe121a',
    messagingSenderId: '162718586351',
    projectId: 'zoho-9e3e8',
    storageBucket: 'zoho-9e3e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_6EGXO5jOcEnmcS6nfJmzPAogUTOM2UY',
    appId: '1:162718586351:ios:241464283c3f1096fe121a',
    messagingSenderId: '162718586351',
    projectId: 'zoho-9e3e8',
    storageBucket: 'zoho-9e3e8.firebasestorage.app',
    iosBundleId: 'com.example.zovo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_6EGXO5jOcEnmcS6nfJmzPAogUTOM2UY',
    appId: '1:162718586351:ios:241464283c3f1096fe121a',
    messagingSenderId: '162718586351',
    projectId: 'zoho-9e3e8',
    storageBucket: 'zoho-9e3e8.firebasestorage.app',
    iosBundleId: 'com.example.zovo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6LTiu-1PfFXaUlfnnkKtNT2YgWeryAU4',
    appId: '1:162718586351:web:b789194b3f80c438fe121a',
    messagingSenderId: '162718586351',
    projectId: 'zoho-9e3e8',
    authDomain: 'zoho-9e3e8.firebaseapp.com',
    storageBucket: 'zoho-9e3e8.firebasestorage.app',
    measurementId: 'G-WNY77684MQ',
  );
}
